version: '3'

services:
    redis:
        container_name: redis
        image: redis:5
        ports: 
          - 36379:6379
        networks:
          - webnet     
    main:
        container_name: 'main'
        build: .
        command: cargo run
        ports:
            - 5000:3000
        depends_on:
            - redis
        networks: 
            - webnet


networks:
    webnet:
                  